#!/bin/sh

name="$1"
version=${2-`cat .version`}

case "$name" in
  "alfredsgame" | \
  "webrtcgame" | \
  "einarsgame" | \
  "gogglesgame" | \
  "gogglesgame1")
    echo "deploying $name@$version"
    sed -i.tmp 's/^application: .*/application: '"$name"'/' app.yaml
    sed -i.tmp 's/^version: .*/version: '$version'/' app.yaml

    # increment and write the version
    version=$(( version+1 ))
    echo "$version" > .version

    # use python instead of the python-2.5 that is hard coded in appcfg.
    # or ssl won't work on osx.
    python `which appcfg.py` --oauth2 update .
    ;;
  *)
    echo "  invalid app name \"$name\""
    exit 1
esac
