#!/bin/sh

name="$1"

case "$name" in
  "alfredsgame" | \
  "webrtcgame" | \
  "einarsgame" | \
  "gogglesgame" | \
  "gogglesgame1")
    echo "deploying $name"
    sed -i.tmp 's/application: .*/application: '"$name"'/' app.yaml

    # use python instead of the python-2.5 that is hard coded in appcfg.
    # or ssl won't work on osx.
    python `which appcfg.py` --oauth2 update .
    ;;
  *)
    echo "  invalid app name \"$name\""
    exit 1
esac
